# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.

#### Import NumPy (as np)

In [6]:
import numpy as np

#### Set the seed to 0

In [7]:
np.random.seed(0)

#### Create an array of 10 zeros 

In [11]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Create an array of 10 ones

In [15]:
[1 for val in range(1,10) ]

[1, 1, 1, 1, 1, 1, 1, 1, 1]

#### Create an array of 10 fives

In [14]:
[5 for val in range(1,10)]

[5, 5, 5, 5, 5, 5, 5, 5, 5]

#### Create an array of the integers from 10 to 50 (in order)

In [17]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Create an array of all the even integers from 10 to 50

In [20]:
[val for val in range(10,51,2)]

[10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50]

#### Create a 5x5 matrix with values ranging from 0 to 8

In [38]:
np.random.randint(1,8,[5,5])

array([[1, 1, 4, 5, 5],
       [1, 5, 4, 4, 6],
       [1, 1, 5, 6, 5],
       [6, 6, 6, 3, 5],
       [7, 5, 2, 6, 1]])

#### Create a 3x3 identity matrix

In [39]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [41]:
np.random.rand()

0.41810921174800086

#### Use NumPy to generate a 5x5 matrix of 25 random numbers sampled from a standard normal distribution

In [69]:
np.random.normal(size=(5,5))

array([[ 0.35281661, -0.15277442, -1.29868672,  1.27607535,  1.32501405],
       [ 0.20533256,  0.04513402,  2.33962481, -0.27643285, -0.25957698],
       [ 0.36448125,  1.47132196,  1.59277075, -0.25857263,  0.30833125],
       [-1.37808347, -0.31197611, -0.8402904 , -1.00683175,  1.68157672],
       [-0.79228666, -0.53160591,  0.36584879,  1.29782527,  0.48111513]])

#### Create the following matrix (hint: use `linspace` with `reshape`):

Expected result:
```python
array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])
```

In [79]:
np.linspace(0.01, 1, 100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [82]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [83]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [1]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW

```python 
[Output]:
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
```

In [85]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [2]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW

```python 
[Output]:
20
```

In [86]:
mat[3,4]

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW

```python 
[Output]:
array([[ 2],
       [ 7],
       [12]])

```

In [94]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [3]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW

```python 
[Output]:
array([21, 22, 23, 24, 25])

```

In [95]:
mat[4,]

array([21, 22, 23, 24, 25])

In [4]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW

```python 
[Output]:
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

In [97]:
mat[3:5,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Conditional Indexing (AKA fancy indexing)

In [10]:
import numpy as np
np.random.seed(0)

In [172]:
mat = np.random.randint(-5, 50, size=[5,5])
mat

array([[39, 25, 29, -2, -5],
       [24, 39, 39, 39, 46],
       [-5, 12, 24, 22, 29],
       [45, 46, 31, 16, 25],
       [32, 12, 33, 10, -4]])

#### Select all elements that are greater than 5.

Expected result:
```python
array([39, 42, 48, 34, 14, 16, 45, 31, 18, 19, 19,  7, 33, 34, 18, 41, 19,
       12, 32])
```

In [101]:
mat[mat>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25])

#### Select all rows where the first element is less than or equal to 20.

Expected result:
```python
array([[-2, 34,  4, 14, 16],
       [19,  7, -4, 33, 34],
       [18, 41, 19, 12, 32]])
```

In [111]:
mat[np.where(mat[:,0]<=20)]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

### Replace all negative elements with 0.

Expected result:
```python
array([[39, 42, 48,  0,  0],
       [ 0, 34,  4, 14, 16],
       [45, 31, 18,  1, 19],
       [19,  7,  0, 33, 34],
       [18, 41, 19, 12, 32]])
```

In [123]:
mat[np.where(mat[:,]<0)] = 0
mat

array([[23, 47,  0,  5,  8],
       [38,  0, 32,  2, 18],
       [25, 12,  0, 42, 29],
       [11, 46, 13, 45, 37],
       [13, 23, 30, 48, 21]])

### Calculate the sum of all elements that are less than or equal to 5.

Expected result: `5`

In [127]:
sum(mat[np.where(mat[:,]<=5)])

14

### Calculate the mean of all elements in the last column.

Expected result: `20.2`

In [138]:
sum(mat[:,4])

100

#### Count the number of elements that are not equal to 0.

Expected result: `21`

In [147]:
len(mat[np.where(mat[:,]!=0)])

24

#### Replace all elements equal to the maximum value of the matrix with 0.

Expected result:
```python
array([[39, 42,  0,  0,  0],
       [ 0, 34,  4, 14, 16],
       [45, 31, 18,  1, 19],
       [19,  7,  0, 33, 34],
       [18, 41, 19, 12, 32]])
```

In [151]:
mat[np.where(mat[:,]==mat.max())] = 0
mat

array([[ 0, 34, 37, 41,  0],
       [23, 38, 14,  5,  5],
       [ 4, 22, 30,  6, 27],
       [33, 26,  0, 17, 22],
       [16, 28, 39, 36,  0]])

### Math on rows and columns

#### Add 5 to a all mat elements

In [154]:
mat = mat + 5
mat

array([[15, 49, 52, 56, 15],
       [38, 53, 29, 20, 20],
       [19, 37, 45, 21, 42],
       [48, 41, 15, 32, 37],
       [31, 43, 54, 51, 15]])

#### Get the sum of all the values in mat

In [163]:
sum(sum(mat[:]))

567

#### Get the standard deviation of the values in mat

15.007518115931095

#### Get the sum of all the columns in mat

In [164]:
sum(mat[:])

array([183,  93,  91,  88, 112])

#### Get the sum of all the rows in mat

In [173]:
np.sum(mat, axis = 1)

array([ 86, 187,  82, 163,  83])

# Great Job!